version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME:-chatdb}
      POSTGRES_USER: ${DB_USER:-chatuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-Pass}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.12
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "5050:80"
    depends_on:
      - db

  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-chatdb}
      DB_USER: ${DB_USER:-chatadmin}
      DB_PASSWORD: ${DB_PASSWORD:-Pass}
      API_KEY: ${API_KEY:-changname}
      RATE_LIMIT_PER_MINUTE: ${RATE_LIMIT_PER_MINUTE:-120}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-*}
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
