spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chatdb
    username: chatadmin
    password: Pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080

app:
  apiKey: changname
  rateLimitPerMinute: 120
  cors:
    allowedOrigins: "*"
